--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4 (Debian 14.4-1.pgdg110+1)
-- Dumped by pg_dump version 14.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgres; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE postgres WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE postgres OWNER TO postgres;

\connect postgres

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: DATABASE postgres; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON DATABASE postgres IS 'default administrative connection database';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.article (
    id integer NOT NULL,
    img_url text,
    title text NOT NULL,
    price character varying(255) NOT NULL,
    currency character varying(1),
    city character varying(255) NOT NULL,
    "time" character varying(255) NOT NULL,
    description text NOT NULL,
    beds text NOT NULL
);


ALTER TABLE public.article OWNER TO postgres;

--
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.article_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.article_id_seq OWNER TO postgres;

--
-- Name: article_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.article_id_seq OWNED BY public.article.id;


--
-- Name: article id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article ALTER COLUMN id SET DEFAULT nextval('public.article_id_seq'::regclass);


--
-- Data for Name: article; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.article (id, img_url, title, price, currency, city, "time", description, beds) FROM stdin;
1	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/e1/e1956a54-ddec-4de6-89b4-37740f4ca905?rule=kijijica-200-jpg	SINGLE BEDROOMS IN SHARED STUDENT APARTMENTS, CLOSE TO RYERSON	995.00	$	City of Toronto	< 20 hours ago	Single rooms for rent in shared student apartments, classic Victorian style house located in the heart of downtown Toronto (Jarvis & Carlton) **Rental price ranges from $995 to $1,100 per room per ...	Beds: 5+
2	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/e2/e2dfc515-5306-4f37-a9c5-67e9114d9a11?rule=kijijica-200-jpg	PROMOTION  | Bachelor Suite - Newly Renovated | Call today!	2,009.00	$	Toronto	< 4 hours ago	Hurry! Limited Time offer. Move-in on or before October 1st and get 1-month free rent for October on Select suites Hurry! Limited Time offer. Move-in on or before October 1st and get 1-month free ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Incentives, Virtual Tours &amp; Incredible Suites! Call Today.	Beds: Bachelor/Studio
3	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/eb/eb209d77-c8d5-40af-b82d-9606f3d6d146?rule=kijijica-200-jpg	Two Bedroom Plus Den Penthouse  | Minto Yorkville Penthouse for	10,989.00	$	Toronto	< 7 hours ago	Utilities Included Heat Water Oversized, premium, and pet friendly suites designed with an open concept layout, floor-to-ceiling windows, private balconies, in-suite laundry and storage space, air ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Premium Two Bedroom Plus Den Penthouse Suite	Beds: 2 + Den
4	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/2a/2ab05cf9-cf97-4059-8bc8-9dff16662786?rule=kijijica-200-jpg	Basement for rent in Ajax	1,600.00	$	City of Toronto	02/09/2022	Basement for rent in Ajax $1600 + All Utilities Included Separate Entrance with One Parking space. 2 Bedroom, 1 Bathrrom, Kitchen Separate Laundry No smoking, No pets Preferred for single or couples ...	Beds: 2
5	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/17/17ce341d-eb66-4e34-b723-e0af08878eb0?rule=kijijica-200-jpg	Beautiful 1 Bedroom Apartment Available Downtown Toronto!	1,850.00	$	Toronto	13/08/2022	2-storey one-bedroom unit. This unit has a truly spectacular view! 2 large balconies with stunning views of the Toronto skyline, newly constructed. Perfect for entertaining. All new stainless steel ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                2 storey one bedroom 2 large balconies  stunning views of the Toronto TTC Transit close by newly constructed Perfect for entertaining All new stainless steel appliances incl. over the range  dishwasher Stunning open riser staircase hardwood Downtown	Beds: 1
6	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/ae/aebd8380-1159-48cb-921d-1160e700104e?rule=kijijica-200-jpg	Parkdale Bachelor Apartment for Rent - 140 Jameson Avenue	1,549.00	$	City of Toronto	< 1 minute ago	Current Promotions Please view our available units by clicking on the virtual tour below. Call now: (437) 886-5105Virtual Open House: Please view our available units by clicking on the virtual tour ...	Beds: Bachelor/Studio
7	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/a2/a21e5021-5d2a-4a8f-97e9-73b57f8037b9?rule=kijijica-200-jpg	Parkdale 1 Bedroom Apartment for Rent - 146 Jameson Avenue	1,849.00	$	Toronto	< 1 minute ago	Current Promotions Please view our available units by clicking on the virtual tour below. Call now: (437) 886-5105Virtual Open House: Please view our available units by clicking on the virtual tour ...	Beds: 1
8	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/25/2575339f-5860-479a-b81a-e736d0c54be9?rule=kijijica-200-jpg	Parkdale 1 Bedroom Apartment for Rent - 140 Jameson Avenue	1,899.00	$	City of Toronto	< 1 minute ago	Current Promotions Please view our available units by clicking on the virtual tour below. Call now: (437) 886-5105Virtual Open House: Please view our available units by clicking on the virtual tour ...	Beds: 1
9	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/5c/5ce5c95b-305b-4e86-ac42-5d5ed793c05f?rule=kijijica-200-jpg	Parkdale Bachelor Apartment for Rent - 90 Jameson Avenue	1,599.00	$	City of Toronto	< 1 minute ago	Current Promotions Please view our available units by clicking on the virtual tour below. Call now: (437) 886-5105Virtual Open House: Please view our available units by clicking on the virtual tour ...	Beds: Bachelor/Studio
10	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/fa/fa61647a-e8f1-43cf-9f59-c4dc46aac913?rule=kijijica-200-jpg	Jameson and Lakeshore Parkdale 1 Bedroom Apartment for Rent - 90	1,949.00	$	City of Toronto	< 1 minute ago	Current Promotions Please view our available units by clicking on the virtual tour below. Call now: (437) 886-5105Virtual Open House: Please view our available units by clicking on the virtual tour ...	Beds: 1
11	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/e2/e2833fc5-da2b-404d-86db-1d5f0fc07e27?rule=kijijica-200-jpg	1001 Bay St one bedroom unit for $1950 in the heart of downtown	1,950.00	$	Toronto	< 1 minute ago	Enjoy Carefree Living In This Professionally Managed 1 Bedroom Located In The Highly Desirable "Bay Street Corridor" Neighborhood. Functional Open Floor Plan Including Galley-Style Kitchen With Full ...	Beds: 1
12	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/89/8959ca55-b7b7-4e8d-989d-638f0a4e03f9?rule=kijijica-200-jpg	Brand New 1 Bedroom + Den Condo – Yonge & Eglinton	2,750.00	$	Old Toronto	< 3 minutes ago	Never lived in before brand new 1 bedroom + den condo at Yonge & Eglinton. Spacious 635 Sq Ft and 102 Sq Ft balcony. Building will have a direct connection to both the Yonge St subway line and the ...	Beds: 1 + Den
13	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/89/897fbfe7-a882-4123-b6fd-81e14e4326d2?rule=kijijica-200-jpg	Renovated Bachelor at Davisville Village	2,000.00	$	Toronto	< 9 minutes ago	The Davisville Village Community is a popular neighbourhood located close to the Davisville subway station. The neighbourhood has excellent recreational facilities, schools, shopping, restaurants, ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                225 Davisville Avenue	Beds: Bachelor/Studio
14	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/e4/e439a268-019c-4263-8987-4fbaa85b1081?rule=kijijica-200-jpg	1 Bedroom w/Locker-Aura At College Park-Full CN Tower View	2,600.00	$	Toronto	< 15 minutes ago	Luxurious Aura Condo Located In The Heart Of Downtown Toronto*Sunny Spacious 1 Bedroom Suite Plus Locker, Large Balcony) on 28th floor, With Unobstructed Panoramic Breath-Taking West View* 9' ...	Beds: 1
15	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/96/96253408-064c-4ff8-9593-619ff3ff50dd?rule=kijijica-200-jpg	3 BEDROOM @ 3700 LAWRENCE AVE EAST SCARBOROUGH	2,700.00	$	City of Toronto	< 16 minutes ago	This well maintained property lies behind a row of trees, adjacent to two schools and opposite a small plaza that has its own IGA store. Just down the street are the extensive shops of Cedarbrae Mall ...	Beds: 3
16	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/db/db979e14-1b07-4a20-b987-fb63729d46a8?rule=kijijica-200-jpg	3091 Eglinton Ave. - 2  Bedroom Apartment	2,100.00	$	City of Toronto	< 16 minutes ago	Next to a senior citizens home, this quiet low-rise sits in an ideal Scarborough location. The Eglinton GO station is just a block away and the building faces a public school on a side street. Close ...	Beds: 2
17	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/34/3451a467-06e5-4fe6-a204-dd97b1f1e86f?rule=kijijica-200-jpg	3700 Lawrence Ave. East - 1 Bedroom Apartment	1,900.00	$	Scarborough	< 16 minutes ago	This well maintained property lies behind a row of trees, adjacent to two schools and opposite a small plaza that has its own IGA store. Just down the street are the extensive shops of Cedarbrae Mall ...	Beds: 1
18	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/81/81abcf91-9c7a-46f8-b993-2937ca49fe02?rule=kijijica-200-jpg	3091 Eglinton Ave. - 1 Bedroom Apartment	1,750.00	$	City of Toronto	< 16 minutes ago	Next to a senior citizens home, this quiet low-rise sits in an ideal Scarborough location. The Eglinton GO station is just a block away and the building faces a public school on a side street. Close ...	Beds: 1
19	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/3a/3ad6d3e9-078f-4e40-a257-55efaa1fe8c2?rule=kijijica-200-jpg	3 BDRM APARTMENTS FOR RENT IN SCARBOROUGH	2,450.00	$	Scarborough	< 16 minutes ago	Next to a senior citizens home, this quiet low-rise sits in an ideal Scarborough location. The Eglinton GO station is just a block away and the building faces a public school on a side street. Close ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                COMFORTABLE 2 Bedroom APARTMENTS FOR RENT IN Eglinton SCARBOROUGH AREA	Beds: 3
20	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/b0/b0081380-aca7-4cc4-b7e0-46ae6b6ac078?rule=kijijica-200-jpg	130 Kingston Road - 2bedroom multiplex $1,950	1,950.00	$	City of Toronto	< 16 minutes ago	Location, Location, Location!!! Downtown Buses/Streetcars At Front On Kingston Road, Close To Theatre, Pharmacy, Lcbo, Convenient Stores, Coffee Shops, Restaurants, And The Beaches. Quiet ...	Beds: 2
21	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/d7/d776f350-ecca-4809-9404-930ed829e31e?rule=kijijica-200-jpg	Davisville  Village - Spacious Three Bedroom Townhome	4,600.00	$	City of Toronto	< 25 minutes ago	Exceptional 3 bedroom, 2.5-bathroom executive townhome available for rent conveniently located at Yonge and Balliol Street, close to the scenic Beltline walking trial, walking distance to both ...	Beds: 3
22	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/38/3807a0b8-70c8-44ea-83ac-bc7f1cced8ca?rule=kijijica-200-jpg	3 Bedroom Townhouse for Rent - All Utilities Included! Pool/Gym	3,200.00	$	Toronto	< 33 minutes ago	2 floor - 3 bedroom, 2 washroom townhouse in a condominium building. Building has pool, gym and sauna. Close to Seneca College Newnham Campus, DVP & Arbor Glen Public School. Available immediately. ...	Beds: 3
23	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/9f/9fb08945-fdaa-4aa4-ae9b-a36a2caef45f?rule=kijijica-200-jpg	Beautiful 1 bedroom apt steps to keelesdale subway station	2,000.00	$	City of Toronto	< 33 minutes ago	Located in the Keelesdale neighbourhood, this is a boutique, 6 unit Toronto apartment building. Ideal for a professional working couple. Apts include two separate entrances front and back. Steps to ...	Beds: 1
24	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/9c/9c0879ba-c706-44c9-8464-add457c84967?rule=kijijica-200-jpg	LARGE 3 Bedroom - ALL INCLUDED	3,150.00	$	Toronto	< 37 minutes ago	Tired of tiny noisy rental units? Renovated 1,500 sq. ft., 3 bedroom, 2 full washroom condo is in the heart of Etobicoke and is available September 15th. The living room has large south facing ...	Beds: 3
25	\N	Basement apartment for rent	1,100.00	$	Toronto	< 38 minutes ago	one bed and one one washroom, Steeles and between Bathurst and Yonge. Close to bus stop and school. Michael 416 670 9490	Beds: 1
26	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/3c/3cc6c959-efaa-415a-9826-100a46f39dff?rule=kijijica-200-jpg	2 Bedroom in the heart of Etobicoke! | Get 1 Month FREE Rent!	2,849.00	$	Etobicoke	< 43 minutes ago	Station Place is located at 5249 Dundas St W conveniently located near the Bloor and Kipling intersection. Brand new, never lived in before suites featuring spacious layouts with large bedrooms and ...	Beds: 2
27	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/ff/ff5c8342-7de5-4058-8505-0ffa5f0c0296?rule=kijijica-200-jpg	1 Bed Available October 15th | Get a $500 Credit!	2,199.00	$	Etobicoke	< 43 minutes ago	Station Place is located at 5249 Dundas St W conveniently located near the Bloor and Kipling intersection. Brand new, never lived in before suites featuring spacious layouts with large bedrooms and ...	Beds: 1
28	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/13/13362fbd-5daf-45b9-aba0-afde48ee9462?rule=kijijica-200-jpg	Studio Available November 15th | Get a $500 Credit!	1,999.00	$	Etobicoke	< 43 minutes ago	Station Place is located at 5249 Dundas St W conveniently located near the Bloor and Kipling intersection. Brand new, never lived in before suites featuring spacious layouts with large bedrooms and ...	Beds: Bachelor/Studio
29	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/e4/e499416c-2c87-4c83-b96b-ec5e5fbbb427?rule=kijijica-200-jpg	1 Bedroom available October 1st | Call for more details!	1,999.00	$	Scarborough	< 43 minutes ago	Biggin Court Apartments are located at 1, 2, 3, 5, and 7 Biggin Court in Scarborough, near the Victoria Park Avenue and Eglinton Avenue East intersection. This "Feel at Home" community offers a ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Great Scarborough Location in Victoria Village! Walking distance to Metro, Shopper's Drug Mart & Tim's! Close to DVP and TTC buses 24, 34 and 70!	Beds: 1
30	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/ac/ace4e392-0c3e-4daa-ae3d-e50a1c03bcff?rule=kijijica-200-jpg	1 Bedroom Available October 15th | CALL NOW!	1,925.00	$	Toronto	< 43 minutes ago	Located at 5 Dufresne Court, near the intersection of Don Mills Rd and Eglinton Ave. E, Dufresne Court Apartments has 1, 2, and 3 bedroom suites. Suites offers: Gorgeous parquet flooring Ceramic ...	Beds: 1
31	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/27/27dd7796-f837-4ecd-9c75-b0d5724be548?rule=kijijica-200-jpg	2 Bedroom Available Nov.15th | Kennedy and 401! Call Today!	2,175.00	$	Scarborough	< 43 minutes ago	Located at Kennedy and 401, Antrim Apartments offers one and two-bedroom suites that are ideal for everyone. Suites offer: Parquet flooring Ample storage space (large storage room) Galley-style ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Great Scarborough Location! Walking Distance to Chapters, Metro & Restaurants! 43 Kennedy TTC Bus Outside Your Door!	Beds: 2
32	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/44/44c06435-7e96-4e5a-a750-59ccd2c385a4?rule=kijijica-200-jpg	1 Bed Available November 15th | Call Now!	1,999.00	$	Toronto	< 43 minutes ago	Thorncliffe Park Apartments are located at 27 Thorncliffe Park Drive in Toronto (East York), near the Thorncliffe Park Drive and Overlea Boulevard intersection. The apartment is accessible via TTC ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Schools, Restaurants & Transit! Easy Access to the DVP!	Beds: 1
33	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/64/64f9f913-1b84-40a2-9f64-039725c42556?rule=kijijica-200-jpg	2 Bedroom available Nov.15th -Vic Park/Lawrence Ave E!	2,199.00	$	Scarborough	< 43 minutes ago	Victoria Park Apartments are located in Scarborough near the Lawrence Avenue East and Victoria Park Avenue intersection. The community is highly accessible via public transportation through the DVP ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Great Scarborough Location in Wexford - Close to Schools & Grocery - 54 TTC Bus/Lawrence & DVP	Beds: 2
34	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/b5/b52ee493-874e-441f-b59a-896a66904b7f?rule=kijijica-200-jpg	1 Bed Available October 15th | Call for details!	1,949.00	$	City of Toronto	< 43 minutes ago	Victoria Park Apartments are located in Scarborough near the Lawrence Avenue East and Victoria Park Avenue intersection. The buildings offer apartments for rent such as bachelor, 1 bedroom apartment, ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Great Scarborough Location in Wexford - Close to Schools & Grocery - 54 TTC Bus/Lawrence & DVP	Beds: 1
35	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/67/674118e7-5c65-4c05-b35c-427d586a5212?rule=kijijica-200-jpg	1 bed Available September 15th! | Victoria Park & Eglinton!	1,949.00	$	Scarborough	< 43 minutes ago	Victoria Park Apartments is located at 1631 Victoria Park Ave., near the intersection of Lawrence Ave E and Victoria Park Ave. The buildings offer bachelor, 1 and 2 bedroom, freshly painted suites, ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Conveniently located near Vic Park & Eglinton! Close to shopping, schools & restaurants!	Beds: 1
36	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/b1/b1225f9c-1f2e-4fce-8649-c5809ff860a9?rule=kijijica-200-jpg	Mid-Town Yonge and St Clair Upscale 1 Bedroom (Air Condition)	2,039.00	$	Toronto	< 43 minutes ago	1 Bedroom with 650 sqft. starting at $1,949.00! Check out our website! www.commonwealthtowers.ca CALL , TEXT OR EMAIL TODAY TO BOOK A VIEWING! 416-825-8894 rentyph@outlook.com Upscale Rental Living ...	Beds: 1
37	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/eb/ebf83586-1de7-4c57-9809-f6f0cd815147?rule=kijijica-200-jpg	3 bedroom bungalow house main floor for rent $2650	2,650.00	$	Toronto	< 47 minutes ago	Bright ans spacious 3 bedroom bungalow house main floor unit for rent at $2650. Large family kitchen, living room, dining room, spacious washroom. AAA tenant with job letter, pay stubs, credit report ...	Beds: 3
38	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/b0/b0d89bc5-29e8-4a27-8801-f4ea423ab1bc?rule=kijijica-200-jpg	YONGE STREET TORONTO YONGE AND DREWRY 1BED +DEN CONDO RENT $2795	2,795.00	$	Toronto	< 49 minutes ago	North York| Yonge St | Yonge and Drewry|1 BED + DEN CONDO FOR RENT DESCRIPTION: Beautiful 1-bedroom newly painted condo, steps away from all amenities and Park, you are close to public transit, ...	Beds: 1 + Den
39	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/fe/fed6b310-8aa6-4627-9fc0-2190e4a49ca2?rule=kijijica-200-jpg	Scarborough 1 Bedroom Apartment for Rent - 45 Greenbrae Circuit	1,988.00	$	City of Toronto	< 50 minutes ago	Current Promotions View our units by clicking the virtual tour link, schedule a video tour or make an appointment for in person viewing. (416) 439-2567Virtual Open House: View our units by clicking ...	Beds: 1
40	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/23/236a8745-17ff-46ca-b2bf-e94ee66d25db?rule=kijijica-200-jpg	Downtown condo for rent	2,700.00	$	Toronto	< 50 minutes ago	Lakefront condo in Toronto (1 bedroom + Den, and 1 parking spot) available for rent starting October 1st of 2022 Price: $2700 + Utilities Address: 15 Queens Quay Unit 706 Condo comes fully furnished ...	Beds: 1 + Den
41	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/c8/c8ede1b6-ddd7-4d90-a1fd-7ed43276fc68?rule=kijijica-200-jpg	Etobicoke 2 Bedroom Apartment for Rent - 40 Stevenson Road	2,249.00	$	Etobicoke	< 54 minutes ago	Current Promotions View our units by clicking the virtual tour link, schedule a video tour or make an appointment for in person viewing. (437) 237-8128Virtual Open House: View our units by clicking ...	Beds: 2
42	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/b9/b952ce18-53fc-4464-9174-a4572893dbc7?rule=kijijica-200-jpg	Etobicoke 1 Bedroom Apartment for Rent - 40 Stevenson Road	2,149.00	$	Etobicoke	< 54 minutes ago	Current Promotions View our units by clicking the virtual tour link, schedule a video tour or make an appointment for in person viewing. (437) 237-8128Virtual Open House: View our units by clicking ...	Beds: 1
43	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/b3/b3dbf774-46b1-41db-b451-66229357e99e?rule=kijijica-200-jpg	Live in The Beaches ~ Renovated Bachelor	1,750.00	$	Toronto	< 56 minutes ago	2367 Queen St East,Scarborough (The Beaches) Queen St. E & Victoria Park Ave Monthly rent: Starting from $1750/month Utilities: Heat included, hydro and water extra Suite Features: Thorough cleaning ...	Beds: Bachelor/Studio
44	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/42/42935823-a53f-4a1d-834f-7d201c495634?rule=kijijica-200-jpg	NEW RENOS, LARGE 1 Bed (North York) Near Hwy 400/401	1,955.00	$	Toronto	< 56 minutes ago	2801 Jane St. Jane St. & Finch Ave. W Rent: Starting from $1955/month Utilities: Heat included Parking: $95 per month/indoor OR $85 per month/outdoor Suite Features: Spacious layouts Thorough ...	Beds: 1
45	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/a5/a57dae77-0a43-4e24-b1dd-f9472947d920?rule=kijijica-200-jpg	Renovated 1 Bedroom  ~ near DVP!	2,080.00	$	City of Toronto	< 56 minutes ago	74 Curlew Drive (North York) Lawrence Ave E. & Victoria Park Ave. Monthly rent: Starting from $1999/month Utilities: Heat included, hydro and water extra Parking: $135 per month/indoor or $120 per ...	Beds: 1
46	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/2f/2f710d63-3307-48cd-bd38-470dcd48abb2?rule=kijijica-200-jpg	1 Bedroom Large Apt. for Rent Steps to Victoria Park Station!	2,025.00	$	City of Toronto	02/09/2022	Touch free leasing: Virtual viewings via video conferencing and online leasing available. Book yours today. Our Rental Office remains operational in light of COVID-19. The health and safety of you, ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Proudly Managed by Realstar Management! Cambridge Place Apartments Offers Bachelor, 1, 1-Bedroom Large, 2 and 3-Bedroom Suites! Office Open Daily!	Beds: 1
47	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/7b/7b8aedbf-d31f-4060-a454-39c3bd4295e9?rule=kijijica-200-jpg	2 BEDROOM  NOVEMBER 202 THE WEST MALL	2,450.00	$	City of Toronto	03/09/2022	Large 2 Bedroom Apartment Available November at the best part of the West Mall. Clean, Well Maintained Building. Parking, Gas, Water, Storage Included, Hydro Extra	Beds: 2
48	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/21/21b82173-a87b-4f06-952d-73bb3caa1e1e?rule=kijijica-200-jpg	Newly Designed 1 Bdrm. for Rent  - Woodbine/Gerrard East	2,150.00	$	City of Toronto	01/09/2022	Touch free leasing:Virtual viewings available via video conferencing. Book yours today. Our Rental Office remains operational in light of COVID-19. The health and safety of you, employees, residents ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Proudly Managed by Realstar Management!  Beachhill Apartments Offers Premium 1 Bedroom, 1 Bedroom + Den, 2 Bedroom and Penthouse Suites!  Up to $1500 in Move-in Bonuses on Select Suites Rented by April 30th!* Office Open Daily!	Beds: 1
49	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/4a/4acc1976-d391-44a8-b12c-7b23d2778862?rule=kijijica-200-jpg	For Rent: Ground-floor furnished studio apartment with backyard	1,700.00	$	City of Toronto	< 18 hours ago	Spacious, furnished, beautiful ground-floor studio apartment with backyard and private laundry amenities. All utilities included. Studio features: - Furnishing - Fridge - Cooktop - Microwave/Oven - ...	Beds: Bachelor/Studio
50	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/68/68a8204f-18cd-426b-b263-ad7199138cdf?rule=kijijica-200-jpg	1 Bedroom Apartments for Rent in the North York	1,725.00	$	City of Toronto	< 6 hours ago	Join us for our Open House Every Saturday from 11:00 - 1:00pm To view our property from the comfort of your own home, click the virtual tour link above! Virtual tours and exterior renderings are for ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Enjoy Condo Living Without the Fees	Beds: 1
51	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/92/926d5cc1-5dba-4918-847e-17f04e3b3d52?rule=kijijica-200-jpg	Luxury Bachelor ~~ Mid-Rise Building in The Beaches!	1,820.00	$	City of Toronto	< 56 minutes ago	1150 & 1200 Kingston Rd., The Beaches Victoria Park Ave. & Kingston Rd. Monthly rent: Starting from $1820/month Utilities: Heat included, hydro and water extra Parking: $120 per month/indoor To view ...	Beds: Bachelor/Studio
52	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/28/2808a0a8-fd71-4869-8fb5-0941c34efd65?rule=kijijica-200-jpg	Gorgeous 1 Bedroom in The Beaches! Pet Friendly, quiet mid-rise!	1,825.00	$	Toronto	< 56 minutes ago	1150 & 1200 Kingston Rd., The Beaches Victoria Park Ave. & Kingston Rd. Monthly rent: Starting from $1825/month Utilities: Heat included, hydro and water extra Parking: $120 per month/indoor To view ...	Beds: 1
53	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/13/13f2e64f-747f-407c-ba30-95b24d2a1690?rule=kijijica-200-jpg	Renovated 1 bedroom in The Beaches ~~ Open House Saturdays!	1,849.00	$	Toronto	< 56 minutes ago	3000, 3015 & 3017 Queen St. E., Scarborough (The Beaches) Queen St. E & Victoria Park Ave. Monthly rent: Starting from $1849/month Utilities: Heat and water included, hydro extra Parking: $130 per ...	Beds: 1
54	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/50/507fd400-b490-44d6-bcd4-25ddf3694515?rule=kijijica-200-jpg	LARGE Renovated 1 Bedroom ~ In The Beaches!	1,822.00	$	City of Toronto	< 56 minutes ago	2402-2406 Queen St East,Scarborough (The Beaches) Queen St. E & Victoria Park Ave. Monthly rent: Starting from $1822/month Utilities: Heat and water included, hydro extra Parking: $118 per month Join ...	Beds: 1
55	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/5a/5affe9a2-5de6-4c18-8613-9a23b0ffabfb?rule=kijijica-200-jpg	SPACIOUS 2 Bedroom in The Beaches ~~ Open House Saturdays!	2,433.00	$	Toronto	< 56 minutes ago	3000, 3015 & 3017 Queen St. E., Scarborough (The Beaches) Queen St. E & Victoria Park Ave. Monthly rent: Starting from $2433/month Utilities: Heat and water included, hydro extra Parking: $130 per ...	Beds: 2
56	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/df/df19201e-1f20-4342-b4e4-cbdd124141d4?rule=kijijica-200-jpg	Large Bachelor at Warden Station - $500GC promo available	1,710.00	$	Scarborough	< 56 minutes ago	50 Burnhill Rd., Scarborough Burnhill Rd. & Warden Ave. Monthly rent: Starting from $1710/month Utilities: Heat included, water and hydro extra Parking: $145 per month/indoor OR $110 per ...	Beds: Bachelor/Studio
57	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/21/21825f80-2f7d-4b2e-8641-863c5d28d6df?rule=kijijica-200-jpg	Renovated 1 Bedroom!  4 Appliances & Balcony! Upper Beaches	1,725.00	$	Scarborough	< 56 minutes ago	1080 Kingston Rd., The Beaches Victoria Park Ave. & Kingston Rd. Monthly rent: Starting from $1725/month Utilities: Heat included, hydro and water extra Parking: $127 per month/indoor and $100 per ...	Beds: 1
73	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/88/882803d9-b19f-4f11-a6d3-a29ae8cec4dd?rule=kijijica-200-jpg	2 Bedroom 2 Bath - Popular Major Oaks Area, Pickering	2,100.00	$	Pickering	< 2 hours ago	Main Floor and Basement Only - Walk To Pickering Mosque Masjid Usman, Hwy 401, Shopping ( Walmart, Sobeys, Cnd Tire, Lowes, No Frills, Bank + More), Credit Score 700+; 40% utilities payable	Beds: 2
58	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/f3/f3534288-0192-4c57-991b-ad49966d67e5?rule=kijijica-200-jpg	BRAND NEW 2 Bedroom, 4 Appliances, Lots of storage! Pet Friendly	2,299.00	$	Scarborough	< 56 minutes ago	1080 Kingston Rd., The Beaches Victoria Park Ave. & Kingston Rd. Monthly rent: Starting from $2,299 Utilities: Heat included, hydro and water extra Parking: $127 per month/indoor and $100 per ...	Beds: 2
59	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/60/6066cf10-7cfd-466f-a3aa-32927ef332c4?rule=kijijica-200-jpg	3 Bedroom  Pent House Apartment for Rent on Jackes Avenue	8,995.00	$	Toronto	< 2 hours ago	Join Us for Our In-person Open House Every Wednesday and Friday from 4pm to 6pm By appointment only. Call Now to Reserve Your Spot! The Summerhilll at 7 Jackes Avenue is an amazing luxury residence ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Ask About our Rental Incentive!	Beds: 3
60	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/54/5445449f-e14c-4187-9d64-c30aa3a45f8f?rule=kijijica-200-jpg	2 Bedroom Apartments for Rent on Jackes Avenue	3,384.00	$	Toronto	< 2 hours ago	Join Us for Our In-person Open House Every Wednesday and Friday from 4pm to 6pm By appointment only. Call Now to Reserve Your Spot! The Summerhilll at 7 Jackes Avenue is an amazing luxury residence ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Ask About our Rental Incentive!	Beds: 2
61	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/02/02d7065f-7b8d-4139-8da7-2ae66fce2b8d?rule=kijijica-200-jpg	1 Bedroom Apartments for Rent on Jackes Avenue	2,550.00	$	Toronto	< 2 hours ago	Join Us for Our In-person Open House Every Wednesday and Friday from 4pm to 6pm By appointment only. Call Now to Reserve Your Spot! The Summerhilll at 7 Jackes Avenue is an amazing luxury residence ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Ask About our Rental Incentive!	Beds: 1
62	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/a0/a09352ae-b20e-4c82-8b05-9629a54bdd00?rule=kijijica-200-jpg	Jr 1 Bedroom Apartments for Rent on Jackes Avenue	2,050.00	$	Toronto	< 2 hours ago	Join Us for Our In-person Open House Every Wednesday and Friday from 4pm to 6pm By appointment only. Call Now to Reserve Your Spot! The Summerhilll at 7 Jackes Avenue is an amazing luxury residence ...\n                        \n                            \n                            \n                                \n                            \n                            \n                        \n\n                        \n                            \n                                Ask About our Rental Incentive!	Beds: 1
63	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/51/513f47ee-1b50-4c17-ab91-84ec7e0a75d6?rule=kijijica-200-jpg	Forest Hill Bachelor Apartment For Rent At Avenue & St. Clair	1,700.00	$	Old Toronto	< 2 hours ago	Unfurnished large bachelor apartment in the prestige Forest Hill neibourhood at Avenue & St. Clair! Very bright with large windows overlooking Forest Hill. Very clean and safe. Streetcar station at ...	Beds: Bachelor/Studio
64	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/41/4101ebeb-4309-4074-877a-5b82588be1f8?rule=kijijica-200-jpg	Lower level apartment for rent November 1 (Bloor / Landsdowne)	1,550.00	$	Toronto	< 2 hours ago	Bright renovated one bedroom lower ground floor apartment in a detached house. Available November 1st. Separate entrance, Ensuite washer / dryer, new kitchen with new appliances and air conditioning. ...	Beds: 1
65	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/53/53d84bdf-ab52-44a6-85e3-6476e0116cd0?rule=kijijica-200-jpg	3 Beds 3 Baths House for Rent	3,000.00	$	Toronto	< 2 hours ago	Features include, spacious open concept layout, kitchen-dining and living room areas. Kitchen features Include NEW granite counter top, cabinets and new silverware appliances including two fridges ...	Beds: 3
66	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/86/86c2972b-83f0-4d1e-a433-6744004bdd2c?rule=kijijica-200-jpg	North York Spacious 2 bedroom Apt Steps to Glencairn Subway Stn	2,400.00	$	Toronto	< 2 hours ago	Available to move in NOW! Spacious Unfurnished 1600 squares foot 2-bedroom apartment in the lower level of a custom-build house. Lots of windows and lights. High ceiling. Heated flooring. Central ...	Beds: 2
67	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/f7/f78b905e-724a-47e5-940e-ec5d129d6265?rule=kijijica-200-jpg	►►► 1BR Renovated Unit in heart of Corso Italia-Avail. Nov 1 ►►►	1,695.00	$	Toronto	< 2 hours ago	Prime trendy Corso Italia Available Nov 1 !!! **Bright large NEWLY RENOVATED 1 bedroom Unit in a quiet low rise building in prime Corso Italia in the walkout raised basement with its’ own private 2 ...	Beds: 1
68	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/6f/6f8e11bd-0189-4373-a8bb-5b98102f338c?rule=kijijica-200-jpg	2 Bedroom Townhouse Condo	2,950.00	$	Toronto	< 2 hours ago	**Apply at https://liv.rent/listings/jnzM528zwm** Entire Townhouse at 76 Munro St Unit Details: - 2 bedroom - 2.0 bathroom - Size: 885 sqft - Furniture available Rental Terms and Conditions: - Max. ...	Beds: 2
69	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/5d/5d8e5568-eca4-47f2-927c-d937179eacf4?rule=kijijica-200-jpg	2 Bedroom Furnished Condo Rental - Downtown Bloor/Spadina	3,350.00	$	Toronto	< 2 hours ago	Beautiful 2 Bedroom 2 Bath fully furnished condo for rent, Bloor and Spadina near University of Toronto in the Annex. Nov 1sth, 2022 Move in date (October 15th can be arranged for earlier move in). ...	Beds: 2
70	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/3b/3b206cff-c577-47bc-b724-4e568d0d78e7?rule=kijijica-200-jpg	►►► 1BR Appartment by the lake-Avail. November 1 ►►►	1,795.00	$	Toronto	< 2 hours ago	Nice & bright south etobicoke by the lake 1 BR unit Available November 1 **Bright open concept Studio Unit in a quiet low rise building by the lake **5 min walk from Humber College **High ceilings, ...	Beds: 1
71	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/4e/4e63187d-d728-4b6c-aaf1-ad7f6927b474?rule=kijijica-200-jpg	Bachelor Apartment Above Store For Rent	1,275.00	$	North York	< 2 hours ago	Do not reply through Kijiji. Call 416 879-9164 Located on Avenue Rd. between Wilson Ave and Lawrence Ave. BACHELOR APARTMENT WITH NEW FLORRING AND OPEN CONCEPT FOR RENT ABOVE STORE 1275.00+ HYDRO. ...	Beds: Bachelor/Studio
72	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/14/14ecd34d-8925-4330-b2b0-9c964ee67b41?rule=kijijica-200-jpg	1 Bdrm available at 77 Huntley Street, Toronto	2,010.00	$	Toronto	< 2 hours ago	Visit our Website: https://www.rpmsi.ca/property/huntley-apartments-77-huntley/ Come experience the Huntley Apartments. Featuring balconies and other upgrades, and only steps away from Sherbourne ...	Beds: 1
74	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/5c/5ca83aba-6702-4f41-acc1-b4dda510c776?rule=kijijica-200-jpg	**Condo For Lease** Scarborough*Close to TTC/Mall***	2,400.00	$	Toronto	< 2 hours ago	Beautiful & Well Maintained Unit In An Excellent Location! Walking Distance To Ttc, School, Library, Shopping Mall & Park. 5 Mins To Hwy 401, 24 Hrs Gated Security. Fantastic Recreational Amenities. ...	Beds: 2
75	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/6d/6d9fa1b3-4385-4c80-9e5c-3c533a2a5dbb?rule=kijijica-200-jpg	3 bedroom apt 2nd floor 794 Ellesmere	2,000.00	$	Toronto	< 2 hours ago	Very spacious Walking distance to: Supermarkets Schools Transit Extra parking available if needed	Beds: 3
76	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/e1/e1a460f6-1943-4114-8aa1-de5d9cf92f3c?rule=kijijica-200-jpg	Downtown 1 Bedroom Luxury Apartment for Rent - 201 Sherbourne St	2,099.00	$	Toronto	< 2 hours ago	Current Promotions View our units by clicking the virtual tour link, schedule a video tour or make an appointment for in person viewing. (647) 699-1574Virtual Open House: View our units by clicking ...	Beds: 1
77	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/c5/c51ab9a0-1add-41a1-993e-3a609f8c6cca?rule=kijijica-200-jpg	Downtown 1 Bedroom Apartment for Rent - 201 Sherbourne Street	2,025.00	$	Toronto	< 2 hours ago	Current Promotions View our units by clicking the virtual tour link, schedule a video tour or make an appointment for in person viewing. (647) 699-1574Virtual Open House: View our units by clicking ...	Beds: 1
78	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/21/2165386f-05ea-4e31-868a-3e5dc9870bc4?rule=kijijica-200-jpg	1 Bedroom Furnished Apartment Downtown Toronto Apartment for Ren	2,700.00	$	City of Toronto	< 2 hours ago	Welcome to Sherbourne Estates located at 201 Sherbourne Street in the heart of downtown Toronto. Sherbourne Estates is a quiet residential property surrounded by well kept grounds. 201 Sherbourne ...	Beds: 1
79	https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/27/27924643-a22c-43d3-ac03-4028f3de06ac?rule=kijijica-200-jpg	Downtown 2 Bedroom Apartment for Rent - 201 Sherbourne Street	2,575.00	$	Toronto	< 2 hours ago	Current Promotions View our units by clicking the virtual tour link, schedule a video tour or make an appointment for in person viewing. (647) 699-1574Virtual Open House: View our units by clicking ...	Beds: 2
80	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/47/478e2c07-8fd9-4953-8ed8-d4b4fea8ef59?rule=kijijica-200-jpg	3+1 Bedroom House for Rent in Scarborough	3,000.00	$	Toronto	< 3 hours ago	This house is located at 7 Cockburn Drive, Scarborough, offers 3 spacious bedrooms on the main floor and a Jumbo room in the basement with Fireplace. Beautiful backyard surrounded by beautiful green ...	Beds: 4
81	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/e9/e942540e-9193-4ee2-b9c9-2f3255362d44?rule=kijijica-200-jpg	Basement bachelor apartment + office for rent in Corso Italia	1,500.00	$	Toronto	< 3 hours ago	Renovated and clean bachelor apartment + full size office available for rent. 1 block away from St. Clair Avenue West. Nearby TTC, shopping, restaurants, bars, parks and so much more. Utilities and ...	Beds: Bachelor/Studio
82	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/3b/3bd704d6-09a1-482e-ab92-892e07c47916?rule=kijijica-200-jpg	condo for rent	2,650.00	$	Toronto	< 3 hours ago	"BRAND NEW" 2 bedroom, 2 bathroom condo, walking distance to shopping, 5 minute drive to 401, very close to schools, parks, community center, 2 kms from new hospital. In suite full size washer\\dryer, ...	Beds: 2
83	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/aa/aae82202-fa83-40c4-bdb1-0d819017f773?rule=kijijica-200-jpg	One bedroom corner condo for rent in heart of Toronto downtown	2,600.00	$	Toronto	< 3 hours ago	Beautiful and functional one bed room corner unit available for rent. Beautiful views, carpet free in a peaceful and quiet building. Comes with a locker. Hydro and internet by tenant.	Beds: 1
84	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/64/647768cf-cfb8-42ab-a5fe-e1966c1ed5b0?rule=kijijica-200-jpg	Stunning Brand New 2 Bed 2 Bath unit with CN tower and lake view	3,100.00	$	Toronto	< 3 hours ago	Stunning city, CN tower and water views!! Never lived in, 2 bedroom 2 bathroom condo with parking in the brand new Mirabella Condo Development. Top of the line finishes and appliances throughout. ...	Beds: 2
85	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/24/24bacb92-d2d7-408d-bf4d-1d80a2219283?rule=kijijica-200-jpg	Lease Assignment (1 br + den 626 sq. ft.) DT condo (Yng/Rich)	2,400.00	$	Toronto	< 3 hours ago	[What?] A 4-month lease assignment from December 1, 2022 to March 31, 2023. This is for a 1-bedroom + den condo unit. You may continue month-to-month afterwards. [How much?] The rent will be $2,150 ...	Beds: 1 + Den
86	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/a4/a444ccf4-6ff9-4803-9921-9e4da4e8a086?rule=kijijica-200-jpg	1 Bdrm 1 Bath + Den BASEMENT	2,295.00	$	Toronto	< 3 hours ago	VERY BRIGHT, MODERN LARGE 1 BDRM + DEN 1BATH BASEMENT UNIT This unit is in one of the best locations in Toronto, you’ll be within walking distance to everything. For example: boutique cafes, grocery ...	Beds: 1 + Den
87	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/24/24ed940d-83f6-4cee-9b84-1eb52665a811?rule=kijijica-200-jpg	3+1 Bedroom House for Rent in Scarborough	3,000.00	$	Toronto	< 3 hours ago	Hello, This house is located at 7 Cockburn Drive, scarborough. Placed in the desirable community, this house offers spacious 3 bedrooms on the main floor and a giant room with fireplace in the ...	Beds: 4
88	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/e6/e6a1cabe-0df0-43c0-a82c-a7a9ef0cebf8?rule=kijijica-200-jpg	3+1 Bedroom House for Rent in Scarborough	3,000.00	$	Toronto	< 3 hours ago	This house located at 7 cockburn drive is a dream house. Situated in the niche community, surrounded by big parks, close to 401, shopping complexes and schools. This house offers 3 spacious room on ...	Beds: 4
89	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/24/24c569d6-a657-4cf9-b6be-a6c22f0d226a?rule=kijijica-200-jpg	Fully Furnished Studio for Rent	2,100.00	$	Toronto	< 3 hours ago	Fully furnished studio apartment for rent downtown. I’ve lived here a year but unfortunately have to move out due to certain commitments. The landlord is absolutely great. The move in date is October ...	Beds: Bachelor/Studio
90	https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/c8/c86e62fb-37cb-46c7-9407-63773f07ddcf?rule=kijijica-200-jpg	FULLY RENOVATED LARGE 1 BR APARTMENT	1,700.00	$	Toronto	< 3 hours ago	Take a chance because there are only two 1 BR. Apartments on the entire floor laundry as well. The Building is in exclusive environments, with many types of Shops and Ristorantes also only 2 minutes ...	Beds: 1
\.


--
-- Name: article_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.article_id_seq', 90, true);


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

