version: "3.9"

services:
  app:
    build: ./
    command: python3 main.py
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=qwerty123
    ports:
      - 58060:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
